//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuctapCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public long assignment_id { get; set; }
        public long employee_id { get; set; }
        public long order_id { get; set; }
        public Nullable<System.DateTime> assigned_date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
    }
}
