//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuctapCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderAssignments = new HashSet<OrderAssignment>();
        }
    
        public long order_id { get; set; }
        public long customer_id { get; set; }
        public string receiver_name { get; set; }
        public string receiver_street { get; set; }
        public Nullable<long> ward_id { get; set; }
        public string receiver_phone { get; set; }
        public decimal order_price { get; set; }
        public decimal shipping_fee { get; set; }
        public Nullable<System.DateTime> warehouse_date { get; set; }
        public Nullable<System.DateTime> shipping_date { get; set; }
        public string status { get; set; }
        public string return_reason { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAssignment> OrderAssignments { get; set; }
    }
}
